project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Exercise 1
            href: Hands_on_Ex/Hands_on_Ex01/Hands_on_Ex01.html
          - text: Hands-on Exercise 2
            href: Hands_on_Ex/Hands_on_Ex02/Hands_on_Ex02.html
            
          - text: Hands-on Exercise 3
            
          - text: Hands-on Exercise 4
            
          - text: Hands-on Exercise 5
            
            
      - text: In-class Exercises
        menu: 
          - text: In-class Exercise 1
            href: In_class_Ex/In_class_Ex01/In_class_Ex01.html
          - text: In-class Exercise 2
            
          - text: In-class Exercise 3
            
          - text: In-class Exercise 4
            
          - text: In-class Exercise 5
            
            
      - text: Take-home Exercises
        menu: 
          - text: Take-home Exercise 1
            
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

