project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Exercise 1
            href: Hands_on_Ex/Hands_on_Ex01/Hands_on_Ex01.html
            
          - text: Hands-on Exercise 2
            href: Hands_on_Ex/Hands_on_Ex02/Hands_on_Ex02.html
            
          - text: Hands-on Exercise 3
            href: Hands_on_Ex/Hands_on_Ex03/Hands_on_Ex03.html
            
          - text: Hands-on Exercise 4
          
          
          - text: Hands-on Exercise 5
          
            
      - text: In-class Exercises
        menu: 
          - text: In-class Exercise 1
            href: In_class_Ex/In_class_Ex01/In_class_Ex01.html
            
          - text: In-class Exercise 2
            href: In_class_Ex/In_class_Ex02/In_class_Ex02.html
            
          - text: In-class Exercise 3
            href: In_class_Ex/In_class_Ex03/In_class_Ex03.html
            
          - text: In-class Exercise 4
            href: In_class_Ex/In_class_Ex04/In_class_Ex04.html
            
    
      - text: Take-home Exercises
        menu: 
          - text: Take-home Exercise 1
            href: Take_home_Ex/Take_home_Ex01/Take_home_Ex01.html
            
          - text: Take-home Exercise 2
            href: Take_home_Ex/Take_home_Ex02/Take_home_Ex02.html
          
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

